name: Release

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    permissions: write-all
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get_version.outputs.version }}
          tag_name: ${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Tarball
        run: make srcdist
      - name: Get Path
        id: get_path
        run: echo "::set-output name=path::$(ls dist/*tar.gz)"
      - name: Get Artifact
        id: get_file
        run: echo "::set-output name=artifact::$(ls basename/*tar.gz)"
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $${{ steps.get_path.outputs.path }}
          asset_name: $${{ steps.get_path.outputs.filename }}
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ github.token }}
