name: Release

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    permissions: write-all
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get_version.outputs.version }}
          tag_name: ${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
